import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      ".next/**",
      ".next-playwright/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      // Static export output and Next build cache — not ours to lint.
      "out/**",
      // Generated by `next dev`/`next build` — not ours to lint.
      "next-env.d.ts",
      // Generated by `convex dev`/`convex codegen` — source functions remain linted.
      "convex/_generated/**",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      // Next 16 enables React Compiler advisory rules. Rivet is not adopting
      // the compiler in this auth integration, so retain the reviewed React 19
      // behavior until those state patterns are migrated intentionally.
      "react-hooks/incompatible-library": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  {
    // Playwright specs run in Node against a real browser, not in the app bundle.
    files: ["e2e/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
];

export default config;
