packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  tree-sitter-python: false
  unrs-resolver: true
overrides:
  nanoid: 3.3.18
patchedDependencies:
  convex@1.42.3: patches/convex@1.42.3.patch
