/** Central TanStack Query key factory — mutations invalidate by prefix. */
export const qk = {
  session: ["session"] as const,
  publicOffer: (token: string) => ["publicOffer", token] as const,
  dashboard: (branchId?: string) => ["dashboard", branchId ?? "all"] as const,
  members: (params?: unknown) => ["members", "list", params] as const,
  member: (id: string) => ["members", "detail", id] as const,
  memberTimeline: (id: string, params?: unknown) => ["members", "timeline", id, params] as const,
  plans: (params?: unknown) => ["plans", params] as const,
  gymProfile: ["gymProfile"] as const,
  gymProfileVersions: ["gymProfile", "versions"] as const,
  ptWorkspace: ["pt", "workspace"] as const,
  ptMember: (membershipId: string) => ["pt", "member", membershipId] as const,
  memberships: (params?: unknown) => ["memberships", params] as const,
  membership: (id: string) => ["memberships", "detail", id] as const,
  leads: (params?: unknown) => ["leads", params] as const,
  lead: (id: string) => ["leads", "detail", id] as const,
  tasks: (params?: unknown) => ["tasks", params] as const,
  renewalQueue: (params?: unknown) => ["renewalQueue", params] as const,
  checkIns: (params?: unknown) => ["checkIns", params] as const,
  occupancy: (branchId: string) => ["occupancy", branchId] as const,
  transactions: (params?: unknown) => ["transactions", params] as const,
  receipt: (id: string) => ["receipts", id] as const,
  currentShift: (branchId: string) => ["shifts", "current", branchId] as const,
  shiftTotals: (branchId: string) => ["shifts", "totals", branchId] as const,
  shifts: (params?: unknown) => ["shifts", params] as const,
  reconciliation: (branchId: string, date: string) => ["reconciliation", branchId, date] as const,
  automationRules: ["automationRules"] as const,
  automationRule: (id: string) => ["automationRules", id] as const,
  automationExecutions: (params?: unknown) => ["automationExecutions", params] as const,
  automationExecution: (id: string) => ["automationExecutions", "detail", id] as const,
  automationRunPreview: (ruleId: string) => ["automationRules", ruleId, "runPreview"] as const,
  operationalEmails: (params?: unknown) => ["operationalEmails", params] as const,
  templates: ["templates"] as const,
  audit: (params?: unknown) => ["audit", params] as const,
  approvals: ["approvals"] as const,
  platformGymDetail: (id: string) => ["platform", "gyms", "detail", id] as const,
  settings: ["settings"] as const,
  workspaceAccess: ["workspace", "access"] as const,
  operations: (params?: unknown) => ["operations", params] as const,
  finance: (params?: unknown) => ["finance", params] as const,
  managementReports: (params?: unknown) => ["managementReports", params] as const,
  branches: ["branches"] as const,
  users: (params?: unknown) => ["users", params] as const,
  savedViews: (surface: string) => ["savedViews", surface] as const,
  bulkJobs: ["bulkJobs"] as const,
  duplicateCases: (status?: string) => ["duplicateCases", status ?? "open"] as const,
  onboarding: (audience: string) => ["onboarding", audience] as const,
  customerFinance: (params?: unknown) => ["customerFinance", params] as const,
  customerReceipt: (id: string) => ["customerReceipts", id] as const,
  pushSubscriptions: ["pushSubscriptions"] as const,
  automationMonitoring: ["automationMonitoring"] as const,
  exports: ["exports"] as const,
  workspaceSearch: (query: string) => ["workspaceSearch", query] as const,
  workspaceRecents: ["workspaceRecents"] as const,
  workspacePins: ["workspacePins"] as const,
};

/** Prefixes invalidated after any money/membership-affecting mutation. */
export const INVALIDATE_ALL = [
  "dashboard",
  "members",
  "memberships",
  "plans",
  "gymProfile",
  "pt",
  "leads",
  "tasks",
  "renewalQueue",
  "checkIns",
  "occupancy",
  "transactions",
  "receipts",
  "shifts",
  "reconciliation",
  "audit",
  "approvals",
  "finance",
  "managementReports",
  "savedViews",
  "bulkJobs",
  "duplicateCases",
  "onboarding",
  "customerFinance",
  "customerReceipts",
  "exports",
  "workspaceSearch",
  "workspaceRecents",
  "workspacePins",
] as const;
