/** Central TanStack Query key factory — mutations invalidate by prefix. */
export const qk = {
  session: ["session"] as const,
  dashboard: (branchId?: string) => ["dashboard", branchId ?? "all"] as const,
  members: (params?: unknown) => ["members", "list", params] as const,
  member: (id: string) => ["members", "detail", id] as const,
  memberTimeline: (id: string, params?: unknown) => ["members", "timeline", id, params] as const,
  plans: (params?: unknown) => ["plans", params] as const,
  memberships: (params?: unknown) => ["memberships", params] as const,
  membership: (id: string) => ["memberships", "detail", id] as const,
  leads: (params?: unknown) => ["leads", params] as const,
  lead: (id: string) => ["leads", "detail", id] as const,
  tasks: (params?: unknown) => ["tasks", params] as const,
  renewalQueue: (params?: unknown) => ["renewalQueue", params] as const,
  checkIns: (params?: unknown) => ["checkIns", params] as const,
  occupancy: (branchId: string) => ["occupancy", branchId] as const,
  transactions: (params?: unknown) => ["transactions", params] as const,
  receipt: (id: string) => ["receipts", id] as const,
  currentShift: (branchId: string) => ["shifts", "current", branchId] as const,
  shiftTotals: (branchId: string) => ["shifts", "totals", branchId] as const,
  shifts: (params?: unknown) => ["shifts", params] as const,
  reconciliation: (branchId: string, date: string) => ["reconciliation", branchId, date] as const,
  automationRules: ["automationRules"] as const,
  automationRule: (id: string) => ["automationRules", id] as const,
  automationExecutions: (params?: unknown) => ["automationExecutions", params] as const,
  templates: ["templates"] as const,
  audit: (params?: unknown) => ["audit", params] as const,
  approvals: ["approvals"] as const,
  settings: ["settings"] as const,
  branches: ["branches"] as const,
  users: (params?: unknown) => ["users", params] as const,
};

/** Prefixes invalidated after any money/membership-affecting mutation. */
export const INVALIDATE_ALL = [
  "dashboard",
  "members",
  "memberships",
  "plans",
  "leads",
  "tasks",
  "renewalQueue",
  "checkIns",
  "occupancy",
  "transactions",
  "receipts",
  "shifts",
  "reconciliation",
  "audit",
  "approvals",
] as const;
