import { ArrowRight, BadgeDollarSign, Check, CircleAlert, Clock3 } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { MARKETPLACE_GYMS, SAAS_PLANS } from "@/lib/public/experience-data";

export default function SubscriptionsPage(){return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1480px]">
  <div><p className="eyebrow">Commercial operations</p><h1 className="mt-2 text-[30px] font-semibold tracking-tight">Subscriptions</h1><p className="mt-2 max-w-2xl text-[12.5px] text-ink-2">Plans, trials, renewals, and expansion opportunities across every RIVET tenant.</p></div>
  <section className="mt-7 grid gap-3 sm:grid-cols-3"><Kpi label="Active MRR" value="JD 647.000" detail="4 customer accounts" icon={<BadgeDollarSign/>}/><Kpi label="Trial pipeline" value="JD 79.000" detail="1 gym · converts 5 Aug" icon={<Clock3/>}/><Kpi label="Expansion ready" value="2 gyms" detail="Near branch or member limits" icon={<CircleAlert/>}/></section>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.8fr]">
    <section className="overflow-x-auto border border-line bg-surface"><div className="border-b border-line px-5 py-4"><p className="eyebrow">Customer plans</p><h2 className="mt-1 text-[17px] font-semibold">Current subscriptions</h2></div><table className="w-full min-w-[720px] text-start"><thead><tr className="border-b border-line bg-sunken text-start font-mono text-[8px] uppercase tracking-[.1em] text-ink-3"><th className="px-5 py-3 font-medium">Gym</th><th className="px-4 py-3 font-medium">Plan</th><th className="px-4 py-3 font-medium">Usage</th><th className="px-4 py-3 font-medium">Next bill</th><th className="px-4 py-3 font-medium">Status</th><th/></tr></thead><tbody>{MARKETPLACE_GYMS.map((gym)=><tr key={gym.id} className="border-b border-line last:border-b-0"><td className="px-5 py-4"><p className="text-[12.5px] font-semibold">{gym.name}</p><p className="mt-1 text-[9.5px] text-ink-3">{gym.branchCount} branch{gym.branchCount>1?"es":""}</p></td><td className="px-4 py-4 text-[11.5px]">{gym.rivetPlan}</td><td className="px-4 py-4"><div className="w-28"><div className="h-1 bg-line"><span className="block h-full bg-signal" style={{width:`${Math.min(92,28+gym.memberCount/30)}%`}}/></div><p className="mt-1.5 text-[8.5px] text-ink-3">{gym.memberCount.toLocaleString()} members</p></div></td><td className="px-4 py-4 text-[11px]">{gym.subscriptionStatus==="trial"?"5 Aug 2026":"18 Aug 2026"}</td><td className="px-4 py-4"><span className={gym.subscriptionStatus==="active"?"rounded-full bg-success-bg px-2 py-1 font-mono text-[7.5px] uppercase text-success":"rounded-full bg-info-bg px-2 py-1 font-mono text-[7.5px] uppercase text-info"}>{gym.subscriptionStatus}</span></td><td className="px-4 py-4"><Button asChild variant="ghost" size="icon-sm"><Link href={`/platform/gyms/${gym.id}`} aria-label={`Open ${gym.name}`}><ArrowRight/></Link></Button></td></tr>)}</tbody></table></section>
    <section className="border border-line bg-surface p-5"><p className="eyebrow">Plan catalog</p><h2 className="mt-1 text-[17px] font-semibold">Published pricing</h2><div className="mt-5 grid gap-3">{SAAS_PLANS.map((plan)=><div key={plan.name} className="border border-line p-4"><div className="flex items-center justify-between"><strong className="text-[13px]">{plan.name}</strong><span className="text-[13px] font-semibold">JD {plan.priceMinor/1000}<small className="font-normal text-ink-3"> / mo</small></span></div><ul className="mt-3 grid gap-1.5 text-[9.5px] text-ink-3"><li className="flex items-center gap-1.5"><Check className="size-3 text-success"/>{plan.branches} branches</li><li className="flex items-center gap-1.5"><Check className="size-3 text-success"/>Up to {plan.members.toLocaleString()} members</li></ul></div>)}</div><Button variant="secondary" className="mt-4 w-full">Edit plan catalog</Button></section>
  </div>
</div></div>}
function Kpi({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <div className="border border-line bg-surface p-5"><span className="text-ink-3 [&_svg]:size-4">{icon}</span><p className="mt-6 font-mono text-[8px] uppercase tracking-[.11em] text-ink-3">{label}</p><p className="mt-2 text-[25px] font-semibold">{value}</p><p className="mt-1 text-[10px] text-ink-3">{detail}</p></div>}
