"use client";

"use client";

import { ArrowLeft, Ban, Building2, CalendarClock, CreditCard, ExternalLink, Mail, MapPin, Phone, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useMarketplaceGyms } from "@/lib/providers/experience-provider";

export default function GymAdminDetail({gymId}:{gymId:string}){const gym=useMarketplaceGyms().find((item)=>item.id===gymId);if(!gym)return <div className="p-10">Gym not found.</div>;
  return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1480px]">
    <Link href="/platform/gyms" className="inline-flex items-center gap-2 text-[11.5px] text-ink-3 hover:text-ink"><ArrowLeft className="size-3.5"/>All gyms</Link>
    <div className="mt-6 flex flex-wrap items-start justify-between gap-6"><div className="flex items-center gap-4"><span className="flex size-14 items-center justify-center font-mono text-[11px] font-semibold text-white" style={{backgroundColor:gym.accent}}>{gym.shortName.slice(0,3)}</span><div><div className="flex items-center gap-2"><h1 className="text-[27px] font-semibold tracking-tight">{gym.name}</h1><ShieldCheck className="size-4 text-success"/></div><p className="mt-1 text-[11.5px] text-ink-3">Customer since {gym.joinedAt} · Last active today</p></div></div><div className="flex gap-2"><Button asChild variant="secondary"><Link href={`/customer/gyms/${gym.id}`}>Marketplace profile <ExternalLink/></Link></Button><Button variant="danger"><Ban/>Suspend</Button></div></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="RIVET plan" value={gym.rivetPlan} detail={gym.subscriptionStatus}/><Stat label="Platform health" value={gym.id==="district-strength"?"71 / 100":"94 / 100"} detail="Stable this week"/><Stat label="Active members" value={gym.memberCount.toLocaleString()} detail={`${gym.branchCount} branch${gym.branchCount>1?"es":""}`}/><Stat label="Gym MRR" value={`JD ${(gym.monthlyRevenueMinor/1000).toLocaleString()}`} detail="Reported this month"/></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]">
      <section className="border border-line bg-surface"><div className="border-b border-line px-5 py-4"><p className="eyebrow">Organization</p><h2 className="mt-1 text-[17px] font-semibold">Branches and usage</h2></div><div className="divide-y divide-line">{gym.branches.map((branch,index)=><div key={branch.id} className="grid gap-4 px-5 py-5 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-[13px] font-semibold">{branch.name}</p><p className="mt-1 flex items-center gap-1.5 text-[10.5px] text-ink-3"><MapPin className="size-3"/>{branch.address}</p></div><div className="sm:text-end"><p className="font-mono text-[8px] uppercase tracking-[.1em] text-ink-3">Members</p><p className="mt-1 text-[12px] font-semibold">{Math.round(gym.memberCount/(index+1.6)).toLocaleString()}</p></div><Button size="sm" variant="secondary">Open branch</Button></div>)}</div><div className="grid grid-cols-2 gap-px border-t border-line bg-line sm:grid-cols-4"><Usage icon={<Users/>} label="Staff seats" value={`${Math.min(18,gym.memberCount/70|0)} / ${gym.rivetPlan==="Starter"?8:gym.rivetPlan==="Growth"?25:80}`}/><Usage icon={<Building2/>} label="Storage" value="1.8 GB"/><Usage icon={<CalendarClock/>} label="Automations" value="12 active"/><Usage icon={<CreditCard/>} label="Transactions" value="1,184"/></div></section>
      <div className="grid gap-5"><section className="border border-line bg-surface p-5"><p className="eyebrow">Account owner</p><h2 className="mt-2 text-[17px] font-semibold">Dana Al-Khatib</h2><div className="mt-5 grid gap-3 text-[11.5px] text-ink-2"><p className="flex items-center gap-2"><Mail className="size-3.5 text-ink-3"/>dana@{gym.id}.jo</p><p className="flex items-center gap-2"><Phone className="size-3.5 text-ink-3"/>+962 79 400 1188</p></div><Button variant="secondary" size="sm" className="mt-5">Contact owner</Button></section><section className="night-surface bg-night p-5 text-night-ink"><p className="eyebrow-night">Subscription</p><p className="mt-4 text-[25px] font-semibold">JD {gym.rivetPlan==="Starter"?79:gym.rivetPlan==="Growth"?149:249}.000</p><p className="mt-1 text-[10.5px] text-night-ink-3">Renews 18 August 2026 · Visa •••• 4041</p><div className="mt-5 flex gap-2"><Button variant="night-outline" size="sm">Change plan</Button><Button variant="night-ghost" size="sm">Invoices</Button></div></section></div>
    </div>
    <section className="mt-5 border border-line bg-surface"><div className="border-b border-line px-5 py-4"><p className="eyebrow">Account activity</p><h2 className="mt-1 text-[17px] font-semibold">Platform timeline</h2></div><div className="grid divide-y divide-line md:grid-cols-3 md:divide-x md:divide-y-0">{[["Today · 13:42","Staff session opened","Dana signed into the Abdoun branch."],["28 Jul · 09:10","Invoice paid","RV-1041 paid automatically by Visa."],["24 Jul · 17:21","Plan limits reviewed","Member capacity at 42% of allowance."]].map(([time,title,detail])=><div key={title} className="p-5"><p className="font-mono text-[8px] uppercase tracking-[.1em] text-ink-3">{time}</p><p className="mt-3 text-[12.5px] font-semibold">{title}</p><p className="mt-1 text-[10.5px] leading-relaxed text-ink-3">{detail}</p></div>)}</div></section>
  </div></div>;
}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="border border-line bg-surface p-5"><p className="font-mono text-[8px] uppercase tracking-[.11em] text-ink-3">{label}</p><p className="mt-3 text-[23px] font-semibold">{value}</p><p className="mt-2 text-[10px] capitalize text-ink-3">{detail}</p></div>}
function Usage({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="bg-surface p-4"><span className="text-ink-3 [&_svg]:size-3.5">{icon}</span><p className="mt-4 font-mono text-[7.5px] uppercase tracking-[.1em] text-ink-3">{label}</p><p className="mt-1 text-[12px] font-semibold">{value}</p></div>}
