"use client";

import { ArrowDownToLine, CheckCircle2, CircleAlert, CreditCard, RefreshCcw } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils/cn";

const INVOICES=[
  {id:"RV-1048",gym:"Pulse Lab",amount:"JD 149.000",date:"31 Jul 2026",status:"failed"},
  {id:"RV-1047",gym:"Her House Fitness",amount:"JD 249.000",date:"28 Jul 2026",status:"paid"},
  {id:"RV-1046",gym:"Forge Fitness Club",amount:"JD 249.000",date:"18 Jul 2026",status:"paid"},
  {id:"RV-1045",gym:"District Strength",amount:"JD 0.000",date:"5 Jul 2026",status:"trial"},
  {id:"RV-1044",gym:"Pulse Lab",amount:"JD 149.000",date:"30 Jun 2026",status:"paid"},
];
export default function BillingPage(){const [retried,setRetried]=useState(false);return <div className="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1480px]">
  <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Payments control</p><h1 className="mt-2 text-[30px] font-semibold tracking-tight">Billing & invoices</h1><p className="mt-2 text-[12.5px] text-ink-2">Track SaaS collections, payment retries, and issued invoices.</p></div><Button variant="secondary"><ArrowDownToLine/>Export ledger</Button></div>
  <section className="mt-7 grid gap-3 sm:grid-cols-3"><Card icon={<CreditCard/>} label="Collected in July" value="JD 647.000" detail="98.7% collection rate"/><Card icon={<CircleAlert/>} label="At risk" value={retried?"JD 0.000":"JD 149.000"} detail={retried?"Payment recovered":"1 failed payment"}/><Card icon={<CheckCircle2/>} label="Next payout" value="2 Aug" detail="Net settlement · JD 634.110"/></section>
  {!retried?<section className="mt-5 flex flex-wrap items-center justify-between gap-5 border border-danger/30 bg-danger-bg p-5"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 size-5 text-danger"/><div><h2 className="text-[13px] font-semibold">Pulse Lab payment needs attention</h2><p className="mt-1 text-[10.5px] text-ink-2">Card •••• 1882 was declined. Account remains active through the 3-day grace period.</p></div></div><Button variant="danger" onClick={()=>setRetried(true)}><RefreshCcw/>Retry payment</Button></section>:<section className="mt-5 flex items-center gap-3 border border-success/30 bg-success-bg p-5 text-success"><CheckCircle2 className="size-5"/><div><h2 className="text-[13px] font-semibold">Payment retry succeeded</h2><p className="mt-1 text-[10.5px]">RV-1048 is queued for settlement.</p></div></section>}
  <section className="mt-5 overflow-x-auto border border-line bg-surface"><div className="border-b border-line px-5 py-4"><p className="eyebrow">Invoice ledger</p><h2 className="mt-1 text-[17px] font-semibold">Recent invoices</h2></div><table className="w-full min-w-[660px]"><thead><tr className="border-b border-line bg-sunken font-mono text-[8px] uppercase tracking-[.1em] text-ink-3"><th className="px-5 py-3 text-start font-medium">Invoice</th><th className="px-4 py-3 text-start font-medium">Gym</th><th className="px-4 py-3 text-start font-medium">Issued</th><th className="px-4 py-3 text-end font-medium">Amount</th><th className="px-4 py-3 text-start font-medium">Status</th><th/></tr></thead><tbody>{INVOICES.map((invoice)=><tr key={invoice.id} className="border-b border-line last:border-b-0"><td className="px-5 py-4 font-mono text-[10px]">{invoice.id}</td><td className="px-4 py-4 text-[12px] font-medium">{invoice.gym}</td><td className="px-4 py-4 text-[10.5px] text-ink-3">{invoice.date}</td><td className="px-4 py-4 text-end text-[11.5px] font-semibold">{invoice.amount}</td><td className="px-4 py-4"><span className={cn("rounded-full px-2 py-1 font-mono text-[7.5px] uppercase",invoice.status==="paid"?"bg-success-bg text-success":invoice.status==="failed"&&!retried?"bg-danger-bg text-danger":invoice.status==="trial"?"bg-info-bg text-info":"bg-success-bg text-success")}>{invoice.status==="failed"&&retried?"paid":invoice.status}</span></td><td className="px-4 py-4"><Button variant="ghost" size="icon-sm" aria-label={`Download ${invoice.id}`}><ArrowDownToLine/></Button></td></tr>)}</tbody></table></section>
</div></div>}
function Card({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="border border-line bg-surface p-5"><span className="text-ink-3 [&_svg]:size-4">{icon}</span><p className="mt-6 font-mono text-[8px] uppercase tracking-[.1em] text-ink-3">{label}</p><p className="mt-2 text-[25px] font-semibold">{value}</p><p className="mt-1 text-[10px] text-ink-3">{detail}</p></div>}
