import type { FinancialPostingStatus, PayableStatus, SupplierPaymentMethod } from "../domain/types";
import { createTranslator, type TFunction, type TKey } from "./core";

const payableKeys: Record<PayableStatus, TKey> = { unpaid: "payablesWorkspace.unpaid", partially_paid: "payablesWorkspace.partiallyPaid", paid: "payablesWorkspace.paid", reversed: "payablesWorkspace.reversed" };
const methodKeys: Record<SupplierPaymentMethod, TKey> = { cash: "domain.paymentMethod.cash", bank_transfer: "domain.paymentMethod.bank_transfer", cliq: "domain.paymentMethod.cliq" };
export const payableStatusLabel = (status: PayableStatus, t: TFunction) => t(payableKeys[status]);
export const supplierPaymentMethodLabel = (method: SupplierPaymentMethod, t: TFunction) => t(methodKeys[method]);

export function ledgerStatusLabel(status: FinancialPostingStatus | undefined, t: TFunction = createTranslator("en")): string {
  const keys: Record<FinancialPostingStatus, TKey> = { posted: "payablesWorkspace.posted", reversed: "payablesWorkspace.ledgerReversed", pending: "payablesWorkspace.pending", failed: "payablesWorkspace.failed", not_posted: "payablesWorkspace.notPosted" };
  return t(status ? keys[status] : "payablesWorkspace.notPosted");
}

/** These prefixes are generated by both payables adapters. Only that wrapper is
 * translated: product names, staff-authored descriptions, IDs and references stay
 * exactly as recorded. Unknown/legacy prose is never guessed or rewritten. */
export function payableSourceLabel(source: string, t: TFunction): string {
  const prefixes: Array<[string, TKey]> = [
    ["Purchase order · ", "payablesWorkspace.sourcePurchase"],
    ["Stock received · ", "payablesWorkspace.sourceStock"],
    ["Facility supplies · ", "payablesWorkspace.sourceSupplies"],
    ["Equipment purchase · ", "payablesWorkspace.sourceAcquisition"],
    ["Equipment repair · ", "payablesWorkspace.sourceRepair"],
  ];
  for (const [prefix, key] of prefixes) if (source.startsWith(prefix)) {
    const detail = source.slice(prefix.length);
    return t(key, { detail: prefix === "Purchase order · " && detail === "no lines" ? t("payablesWorkspace.noLines") : detail });
  }
  const fallback = /^Purchase order ([A-Za-z0-9_-]+)$/.exec(source);
  return fallback ? t("payablesWorkspace.sourcePurchaseId", { id: fallback[1]! }) : source;
}

export function payableReconciliationReason(reason: string, t: TFunction): string {
  const keys: Record<string, TKey> = {
    "No supplier was recorded for this purchase. Check this cost in the Management ledger.": "payablesWorkspace.missingPurchaseSupplier",
    "Stock was received without an order. No supplier was recorded.": "payablesWorkspace.missingStockSupplier",
    "This completed maintenance job has a supplies cost. No supplier was recorded.": "payablesWorkspace.missingSuppliesSupplier",
    "This machine has a purchase cost. Its maker’s name does not identify the supplier.": "payablesWorkspace.missingMachineSupplier",
    "This repair cost has no linked supplier bill. The repairer’s name is saved as a note.": "payablesWorkspace.missingRepairSupplier",
  };
  if (keys[reason]) return t(keys[reason]);
  const foreign = /^Recorded in ([A-Z]{3}), not ([A-Z]{3}); settle it with a manual journal\.$/.exec(reason);
  return foreign ? t("payablesWorkspace.foreignCurrency", { recordedCurrency: foreign[1]!, currency: foreign[2]! }) : reason;
}
